ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc-placement!:
toc::[]
endif::[]

:toc: left
:toclevels: 1
:sectnums:
:sectnumlevels: 1
:icons: font
:experimental:
:nofooter:

= Go tour 정리

== Package

* 모든 go 프로그램은 `Package` 로 구성
* 프로그램은 `main` 패키지에서 실행
* 패키지 이름 규칙은 디렉토리 경로의 마지막 이름
* 예를 들어 `path/filepath` 를 사용하면 패키지명은 `filepath`

[source, go]
----
package main <1>

import "fmt"

func main() {
	fmt.Println("Hello world")
}

// ---result---
// Hello world
----
<1> 패키지 선언

== Imports

* 임포트는 다른 패키지를 참조할 때 사용
* 패키지를 참조하는 방법은 2가지
** 소괄호로 감싸서 표현
+
[source, go]
----
import (
    "fmt"
    "math"
)
----
** `import` 문장을 여러번 사용해서 표현
+
[source, go]
----
import "fmt"
import "math"
----

[source, go]
----
package main

import ( <1>
	"fmt"
	"math"
)

func main() {
	fmt.Printf("now you have %g problems.", math.Nextafter(2, 3))
}

// ---result---
// now you have 2.0000000000000004 problems.
----
<1> fmt, math 패키지를 임포트

== Exported names

* 패키지를 임포트하면 패키지가 외부로 export한 메서드나 변수, 상수 등에 접근 가능
* Go에서는 첫 문자가 대문자로 시작하면 그 패키지를 사용하는 곳에서 접근할 수 있는 `exported name` 이 됨
** 접근가능: `Foo`, `FOO`
** 접근불가능: `foo`

[source, go]
----
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.Pi)
	// fmt.Println(math.pi) <1>
}

// ---result---
// 3.141592653589793
----
<1> 에러 발생 (소문자로 시작해서 외부 접근 불가)

== Function

* 함수는 매개변수(인자)를 가질 수 있음
** `add2` 는 두개의 `int` 타입 매개변수를 받음
** `add3` 은 세개의 `int` 타입 매개변수를 받음
* c, c++, java 와 다르게 go 에서는 변수명 뒤에 매개변수 타입을 명시
** 이유는 코드를 왼쪽에서 오른쪽으로 읽을 때 자연스럽게 일기 위해
** 참고: https://blog.golang.org/declaration-syntax[Go's declaration syntax]
* 두 개 이상의 매개변수가 같은 타입일 때, 마지막 매개변수에만 타입을 명시 가능
+
[source, go]
----
x int, y int == x, y int
----
* 함수는 `클로져(full closures)`
** 각각의 클로져는 자신만의 변수를 가질 수 있음

[source, go]
----
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(add2(42, 13))
	fmt.Println(add3(1, 10, 111))

	hypot := func(x, y float64) float64 {
		return math.Sqrt(x*x + y*y)
	}
	fmt.Println(hypot(3, 4)) <1>

	pos, neg := adder(), adder()
	for i := 0; i < 3; i++ {
		fmt.Println(pos(i), neg(-2*i))
	}
}

func add2(x int, y int) int {
	return x + y
}

func add3(x, y, z int) int { <2>
	return x + y + z
}

func adder() func(int) int { <3>
	sum := 0
	return func(x int) int {
		sum += x
		return sum
	}
}

// ---result---
// 55
// 122
// 5
// 0 0
// 1 -2
// 3 -6
----
<1> `hypot` 함수를 `Println` 함수의 인자값으로 사용
<2> 매개변수가 같은 타입이라 마지막에만 타입 명시
<3> 클로져 반환 (각각의 클로져는 자신만의 sum 변수를 갖음)

== Results

* 하나의 함수는 여러 개의 결과를 반환 가능
* 반환 값에 이름을 부여하면 변수처럼 사용

[source, go]
----
package main

import "fmt"

func main() {
	a, b := swap("hello", "world")
	fmt.Println(a, b)

	fmt.Println(split(17))
}

func swap(x, y string) (string, string) { <1>
	return y, x
}

func split(sum int) (x, y int) { <2>
	x = sum * 4 / 9
	y = sum - x
	return
}

// ---result---
// world hello
// 7 10
----
<1> 2개의 string 결과를 반환
<2> 반환 값에 x, y로 이름을 부여하고 return에 빈값 설정

== Variables

* 변수 선언을 위해 `var` 를 사용
* 타입은 문장 끝에 명시
* 변수 선언시 초기화 가능
** 초기화시 타입 생략 가능하고 이런 경우 초기화하는 값에 따라 타입이 결정
* 짧은 선언
** 함수 내에서 가능
** `:=` 를 사용하면 `var` 와 타입 (`int`, `bool` 등) 생략 가능

[source, go]
----
package main

import "fmt"

var x, y, z int <1>
var c, python, java = true, false, "jvm" <2>

func main() {
	fmt.Println(x, y, z)
	fmt.Println(c, python, java)

	jan, feb, mar := "January", "February", "March" <3>
	fmt.Println(jan, feb, mar)
}

// ---result---
// 0 0 0
// true false jvm
// January February March
----
<1> 변수 선언
<2> 변수 선언과 동시에 초기화 (타입 생략)
<3> `:=` 로 var와 타입 생략

== Constants

* 상수 선언은 `const` 키워드를 이용하고 변수처럼 선언
* 숫자형 상수(Numeric Constants)로 정밀한 값을 표현

[source, go]
----
package main

import "fmt"

const (
	Pi    = 3.14
	Big   = 1 << 100
	Small = Big >> 99
)

func main() {
	fmt.Println("Happy", Pi, "Day")

	const Truth = true
	fmt.Println("Go rules?", Truth)

	fmt.Println(needInt(Small))
	fmt.Println(needFloat(Small))
	fmt.Println(needFloat(Big))
}

func needInt(x int) int {
	return x * 10 + 1
}

func needFloat(x float64) float64 {
	return x * 0.1
}

// ---result---
// Happy 3.14 Day
// Go rules? true
// 21
// 0.2
// 1.2676506002282295e+29
----

== If

* c, java 와 비슷하지만 조건 표현시 `( )` 는 사용 안함
* 조건문 앞에 짧은 명령 실행 가능
+
--
[source, go]
----
if v := math.Pow(x, n); v < lim {
    ...
}
----

IMPORTANT: 조건문에서 선언된 변수는 `if-else` 문 안에서만 사용 가능
--

[source, go]
----
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(sqrt(2), sqrt(-4))
	fmt.Println(pow(3, 2, 10), pow(3, 3, 20))
}

func sqrt(x float64) string {
	if x < 0 {
		return sqrt(-x) + "i"
	}
	return fmt.Sprint(math.Sqrt(x))
}

func pow(x, n, lim float64) float64 {
	if v := math.Pow(x, n); v < lim { <1>
		return v
	} else {
		fmt.Printf("%g >= %g\n", v, lim)
	}
    // fmt.Printf(v) <2>
	return lim
}

// ---result---
// 1.4142135623730951 2i
// 27 >= 20
// 9 20
----
<1> 조건문에서 짧은 명령 실행
<2> if-else 문 밖에서는 v 변수 사용 불가

== For

* go 에서는 반복문이 `for` 밖에 없음
* `if` 문 처럼 c, java 와 유사하지만 조건문에 `( )` 가 필요 없음
* 전후처리를 제외하고 조건문만 표현 가능
* 조건문을 생략하면 무한 루프

[source, go]
----
package main

import "fmt"

func main() {
	sum := 0
	for i := 0; i < 10; i++ {
		sum += i
	}
	fmt.Println(sum)

	sum = 1
	for sum < 1000 { <1>
		sum += sum
	}
	fmt.Println(sum)

	sum = 1
	for { <2>
		sum += sum
		if sum > 100 {
			break
		}
	}
	fmt.Println(sum)
}

// ---result---
// 45
// 1024
// 128
----
<1> 조건문만 표현
<2> 무한 루프

== Date Types

* go의 기본 자료형
+
[source, go]
----
bool

string

int  int8  int16  int32  int64
uint uint8 uint16 uint32 uint64 uintptr

byte <1>

rune <2>

float32 float64

complex64 complex128
----
<1> uint8의 다른 이름(alias)
<2> int32의 다른 이름(alias), 유니코드/코드/포인트 표현

[source, go]
----
package main

import (
	"fmt"
	"math/cmplx"
)

var (
	ToBe   bool       = false
	MaxInt uint64     = 1<<64 - 1
	z      complex128 = cmplx.Sqrt(-5 + 12i)
)

func main() {
	const f = "%T(%v)\n"
	fmt.Printf(f, ToBe, ToBe)
	fmt.Printf(f, MaxInt, MaxInt)
	fmt.Printf(f, z, z)
}

// ---result---
// bool(false)
// uint64(18446744073709551615)
// complex128((2+3i))
----

== Structs

* 필드(데이터)들의 조합
* `type` 선언으로 구조체의 이름 지정
* 구조체에 속한 필드(데이터)는 `dot(.)` 으로 접근
* 원하는 필드를 `{Name: value}` 형식으로 할당
+
TIP: 필드 순서는 상관 없음

[source, go]
----
package main

import "fmt"

type Vertex struct {
	X int
	Y int <1>
}

func main() {
	s := Vertex{} <2>
	p := Vertex{X: 1}
	q := Vertex{1, 2}
	q.X = 4
	fmt.Println(s, p, q)
}

// ---result---
// {0 0} {1 0} {4 2}
----
<1> `X, Y int` 로 표현 가능
<2> 따로 설정하지 않으면 `0` 으로 초기화

== Pointers

* go에는 포인터가 있지만 포인터 연산은 불가능
* 구조체 변수는 구조체 포인터로 접근 가능

[source, go]
----
package main

import "fmt"

type Vertex struct {
	X int
	Y int
}

func main() {
	p := Vertex{1, 2}
	q := &p <1>
	q.X = 1e9
	fmt.Println(p)
}

// ---result---
// {1000000000 2}
----
<1> q는 p의 포인터로 접근

== new function

* `new(T)` 는 모든 필드에 `0 (zero value)` 이 할당된 T 타입의 포인터를 반환
+
IMPORTANT: zero value는 숫자 타입에서는 0 , 참조 타입에서는 nil
* 사용방법
+
[source, go]
----
var t *T = new(T)
// 또는 t := new(T)
// 변수 t는 T 에서 반환된 포인터를 갖음
----

[source, go]
----
package main

import "fmt"

type Vertex struct {
	X, Y int
}

func main() {
	v := new(Vertex) <1>
	fmt.Println(v)

	v.X, v.Y = 11, 9
	fmt.Println(v)
}

// ---result---
// &{0 0}
// &{11 9}
----
<1> Vertex 타입의 포인터 반환

== Slices

* 슬라이스는 배열을 의미
* `[]T` 는 타입 T 를 가지는 요소의 슬라이스
* 슬라이스는 분할하거나 같은 배열을 가리키는(point) 새로운 슬라이스를 생성 가능
+
[cols="1,2"]
|===
| 표현 | 설명
| s[lo:hi] | lo 에서 hi-1 의 요소를 포함하는 슬라이스
| s[lo:lo] | 빈 슬라이스
| s[lo:lo+1] | 하나의 요소를 갖는 슬라이스
|===
[[make]]
* `make` 함수로 슬라이스 생성 가능
+
--
[cols="1,2a"]
|===
| 표현 | 슬라이스 정보
| a := make([]int, 5)
| len(a)=5

* 두번째 매개변수로 슬라이스 크기를 설정
| b := make([]int, 0, 5)
| len(b)=0, cap(b)=5

* 세번째 매개변수로 용량을 제한
| b = b[:cap(b)] | len(b)=5, cap(b)=5
| b = b[1:] | len(b)=4, cap(b)=4
|===

NOTE: `make` 로 생성한 슬라이스는 0을 할당한 배열을 생성하고 포인터를 반환
--
* 슬라이스의 zero value는 nil (길이와 최대 크기가 0)

TIP: 참고 http://golang.org/doc/articles/slices_usage_and_internals.html[Slices: usage and internals]

[source, go]
----
package main

import "fmt"

func main() {
	var t []int <1>
	fmt.Println(t, len(t), cap(t))
	if t == nil {
		fmt.Println("nil!")
	}

	p := []int{2, 3, 5, 7, 11, 13} <2>
	fmt.Println("p ==", p)
	fmt.Println("p[1:4] ==", p[1:4])
	fmt.Println("p[:3] ==", p[:3])
	fmt.Println("p[4:] ==", p[4:])

	for i := 0; i < len(p); i++ {
		fmt.Printf("p[%d] == %d\n", i, p[i])
	}

	a := make([]int, 5) <3>
	b := make([]int, 0, 5)
	c := b[:2]
	d := c[2:5]
	printSlice("a", a)
	printSlice("b", b)
	printSlice("c", c)
	printSlice("d", d)
}

func printSlice(s string, x []int) {
	fmt.Printf("%s len=%d cap=%d %v\n", s, len(x), cap(x), x)
}

// ---result---
// [] 0 0
// nil!
// p == [2 3 5 7 11 13]
// p[1:4] == [3 5 7]
// p[:3] == [2 3 5]
// p[4:] == [11 13]
// p[0] == 2
// p[1] == 3
// p[2] == 5
// p[3] == 7
// p[4] == 11
// p[5] == 13
// a len=5 cap=5 [0 0 0 0 0]
// b len=0 cap=5 []
// c len=2 cap=5 [0 0]
// d len=3 cap=3 [0 0 0]
----
<1> 빈 슬라이스
<2> 슬라이스 생성 및 값 초기화
<3> `make` 에 대한 설명은 <<make, 참고>>

== Range
* `for` 문에서 `range` 를 사용하여 슬라이스나 맵을 순회
* `_` 를 이용해서 인덱스나 값를 무시

[source, go]
----
package main

import "fmt"

var pow = []int{1, 2, 4, 8}

func main() {
	for i, v := range pow { <1>
		fmt.Printf("2**%d = %d\n", i, v)
	}

	pow = make([]int, 4)
	for i := range pow { <2>
		pow[i] = 1 << uint(i)
	}
	for _, value := range pow { <3>
		fmt.Printf("%d\n", value)
	}
}

// ---result---
// 2**0 = 1
// 2**1 = 2
// 2**2 = 4
// 2**3 = 8
// 1
// 2
// 4
// 8
----
<1> `i` 는 인덱스, `v` 는 값을 받음
<2> 인덱스만 사용
<3> 값만 사용

== Maps

* 맵은 값에 키를 지정
* 맵 리터럴은 구조체 리터럴과 비슷하지만 key를 반드시 지정해야함
* 맵 요소 설정
+
--
[cols="1,2a"]
|===
| 표현 | 설명
| m[key] = elem | 맵 m의 요소를 삽입/수정
| elem = m[key] | 요소 값 반환
| delete(m, key) | 요소 값 삭제
| elem, ok = m[key]
| 키의 존재 여부 확인

* ok: m에 key가 존재하면 `true` 아니면 `false`
* elem: 존재하지 않는 key의 반환 값은 타입에 맞는 zero value
|===
--

[WARNING]
====
* 맵은 반드시 사용하기 전에 `make` 를 명시 (`new` 가 아님!)
* `make` 를 수행하지 않은 빈 맵에는 값 할당 안됨
====

== Switch

* 다른 언어와 가장 큰 차이는 go에서는 switch의 case 코드 실행이 끝나면 자동으로 break 처리
** `fallthrough` 로 끝날때만 break 하지 않음
* switch에서 조건을 생략하면 `switch true` 와 같음
** 긴 `if-then-else` 를 작성해야 할 때 효과적

[source, go]
----
package main

import (
	"fmt"
	"runtime"
	"time"
)

func main() {
	fmt.Print("Go runs on ")
	switch os := runtime.GOOS; os { <1>
	case "darwin":
		fmt.Println("os x")
	case "linux":
		fmt.Println("linux")
	default:
		fmt.Printf("%s\n", os)
	}

	t := time.Now()
	switch { <2>
	case t.Hour() < 12:
		fmt.Println("Good morning")
	case t.Hour() < 17:
		fmt.Println("Good afternoon")
	default:
		fmt.Println("Good evening")
	}
}

// ---result---
// Go runs on windows
// Good evening
----
<1> switch 문에 짧은 명령문
<2> 조건이 없는 switch 문 (= switch true)

== Methods

* Go 에는 클래스가 없음
** 대신 구조체 또는 타입에 메소드를 붙일 수 있음
** 다른 패키지에 있는 타입 또는 기본 타입에는 불가능
* 메소드 리시버(method receiver)
** func 키워드와 메소드의 이름 사이에 위치
** 포인터 리시버와 밸류 리시버가 있음
** 포인터 리시버를 사용하는 이유
*** 메소드가 호출될 때 마다 값이 복사되는 것을 방지
*** 메소드에서 리시버 포인터가 가르키는 값을 수정하기 위함

[source, go]
----
package main

import (
	"fmt"
	"math"
)

type Vertex struct {
	X, Y float64
}

func (v *Vertex) Abs() float64 { <1>
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}

func (v *Vertex) Scale(f float64) { <2>
	v.X = v.X * f
	v.Y = v.Y * f
}

type MyFloat float64

func (f MyFloat) Abs() float64 { <3>
	if f < 0 {
		return float64(-f)
	}
	return float64(f)
}

func main() {
	v := &Vertex{3, 4}
	fmt.Println(v.Abs())

	v.Scale(5)
	fmt.Println(v.Abs())

	f := MyFloat(-math.Sqrt2)
	fmt.Println(f.Abs())
}

// ---result---
// 5
// 25
// 1.4142135623730951
----
<1> 값을 읽기만 하기때문에 포인터 리시버/밸류 리시버 둘다 상관없음
<2> Vertex 값을 변경하기때문에 포인터 리시버를 써야함
<3> MyFloat 값을 읽기만 하기때문에 밸류 리시버를 써도됨

== Interface

* 메소드의 집합으로 정의
* 메소드의 집합을 구현한 타입의 값은 모두 인터페이스 타입의 값이 될 수 있음
* Go 에서는 인터페이스가 암시적으로 사용
** 타입이 인터페이스의 메소드들을 구현만 하면됨
** 이는 인터페이스를 정의한 패키지로 부터 구현 패키지를 분리함 (의존성 x)

[source, go]
----
package main

import (
	"fmt"
	"math"
	"os"
)

type Abser interface {
	Abs() float64
}

type Reader interface {
	Read(b []byte) (n int, err error)
}

type Writer interface {
	Write(b []byte) (n int, err error)
}

type ReadWriter interface {
	Reader
	Writer
}

type Vertex struct {
	X, Y float64
}

func (v *Vertex) Abs() float64 {
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}

type MyFloat float64

func (f MyFloat) Abs() float64 {
	if f < 0 {
		return float64(-f)
	}
	return float64(f)
}

func main() {
	v := Vertex{3, 4}
	f := MyFloat(-math.Sqrt2)

	var a Abser = &v <1>
	// var a Abser = v
	fmt.Println(a.Abs())
	a = f
	fmt.Println(a.Abs())

	var w Writer = os.Stdout
	fmt.Fprintf(w, "hello writer\n")
}

// ---result---
// 5
// 1.4142135623730951
//  hello writer
----
<1> Vertex와 MyFloat 은 Abs를 구현했기 때문에 Abser 인터페이스

## Error

* Go 에서는 에러 문장(string)으로 자신을 표현할 수 있는 것은 모두 에러
* 이는 문자열을 반환하는 하나의 메소드 Error 로 구성된 내장 인터페이스 타입 error 에서 나옴
+
--
[source, go]
----
type error interface {
	Error() string
}
----
--
* fmt 패키지의 다양한 출력 루틴들은 error 의 출력을 요청받았을 때 자동으로 이 메소드를 호출

[source, go]
----
package main

import (
	"fmt"
	"time"
)

type MyError struct {
	When time.Time
	What string
}

func main() {
	if err := run(); err != nil { <1>
		fmt.Println(err)
	}
}

func (e *MyError) Error() string { <2>
	return fmt.Sprintf("at %v, %s", e.When, e.What)
}

func run() error {
	return &MyError{time.Now(), "it didn't work"}
}

// ---result---
// at 2020-06-24 01:13:40.5127801 +0900 KST m=+0.025986101, it didn't work
----
<1> MyError 값 설정
<2> fmt 패키지에서 출력시 실행