ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc-placement!:
toc::[]
endif::[]

:toc: left
:toclevels: 1
:sectnums:
:sectnumlevels: 1
:icons: font
:experimental:
:nofooter:

= Go tour 정리

== Package

* 모든 go 프로그램은 `Package` 로 구성
* 프로그램은 `main` 패키지에서 실행
* 패키지 이름 규칙은 디렉토리 경로의 마지막 이름
* 예를 들어 `path/filepath` 를 사용하면 패키지명은 `filepath`

[source, go]
----
package main <1>

import "fmt"

func main() {
	fmt.Println("Hello world")
}

// ---result---
// Hello world
----
<1> 패키지 선언

== Imports

* 임포트는 다른 패키지를 참조할 때 사용
* 패키지를 참조하는 방법은 2가지
** 소괄호로 감싸서 표현
+
[source, go]
----
import (
    "fmt"
    "math"
)
----
** `import` 문장을 여러번 사용해서 표현
+
[source, go]
----
import "fmt"
import "math"
----

[source, go]
----
package main

import ( <1>
	"fmt"
	"math"
)

func main() {
	fmt.Printf("now you have %g problems.", math.Nextafter(2, 3))
}

// ---result---
// now you have 2.0000000000000004 problems.
----
<1> fmt, math 패키지를 임포트

== Exported names

* 패키지를 임포트하면 패키지가 외부로 export한 메서드나 변수, 상수 등에 접근 가능
* Go에서는 첫 문자가 대문자로 시작하면 그 패키지를 사용하는 곳에서 접근할 수 있는 `exported name` 이 됨
** 접근가능: `Foo`, `FOO`
** 접근불가능: `foo`

[source, go]
----
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.Pi)
	// fmt.Println(math.pi) <1>
}

// ---result---
// 3.141592653589793
----
<1> 에러 발생 (소문자로 시작해서 외부 접근 불가)

== Function

* 함수는 매개변수(인자)를 가질 수 있음
** `add2` 는 두개의 `int` 타입 매개변수를 받음
** `add3` 은 세개의 `int` 타입 매개변수를 받음
* c, c++, java 와 다르게 go 에서는 변수명 뒤에 매개변수 타입을 명시
** 이유는 코드를 왼쪽에서 오른쪽으로 읽을 때 자연스럽게 일기 위해
** 참고: https://blog.golang.org/declaration-syntax[Go's declaration syntax]
* 두 개 이상의 매개변수가 같은 타입일 때, 마지막 매개변수에만 타입을 명시 가능
+
[source, go]
----
x int, y int == x, y int
----

[source, go]
----
package main

import "fmt"

func main() {
	fmt.Println(add2(42, 13))
	fmt.Println(add3(1, 10, 111))
}

func add2(x int, y int) int {
	return x + y
}

func add3(x, y, z int) int { <1>
	return x + y + z
}

// ---result---
// 55
// 122
----
<1> 매개변수가 같은 타입이라 마지막에만 타입 명시

== Results

* 하나의 함수는 여러 개의 결과를 반환 가능
* 반환 값에 이름을 부여하면 변수처럼 사용

[source, go]
----
package main

import "fmt"

func main() {
	a, b := swap("hello", "world")
	fmt.Println(a, b)

	fmt.Println(split(17))
}

func swap(x, y string) (string, string) { <1>
	return y, x
}

func split(sum int) (x, y int) { <2>
	x = sum * 4 / 9
	y = sum - x
	return
}

// ---result---
// world hello
// 7 10
----
<1> 2개의 string 결과를 반환
<2> 반환 값에 x, y로 이름을 부여하고 return에 빈값 설정

== Variables

* 변수 선언을 위해 `var` 를 사용
* 타입은 문장 끝에 명시
* 변수 선언시 초기화 가능
** 초기화시 타입 생략 가능하고 이런 경우 초기화하는 값에 따라 타입이 결정
* 짧은 선언
** 함수 내에서 가능
** `:=` 를 사용하면 `var` 와 타입 (`int`, `bool` 등) 생략 가능

[source, go]
----
package main

import "fmt"

var x, y, z int <1>
var c, python, java = true, false, "jvm" <2>

func main() {
	fmt.Println(x, y, z)
	fmt.Println(c, python, java)

	jan, feb, mar := "January", "February", "March" <3>
	fmt.Println(jan, feb, mar)
}

// ---result---
// 0 0 0
// true false jvm
// January February March
----
<1> 변수 선언
<2> 변수 선언과 동시에 초기화 (타입 생략)
<3> `:=` 로 var와 타입 생략

== Constants

* 상수 선언은 `const` 키워드를 이용하고 변수처럼 선언
* 숫자형 상수(Numeric Constants)로 정밀한 값을 표현

[source, go]
----
package main

import "fmt"

const (
	Pi    = 3.14
	Big   = 1 << 100
	Small = Big >> 99
)

func main() {
	fmt.Println("Happy", Pi, "Day")

	const Truth = true
	fmt.Println("Go rules?", Truth)

	fmt.Println(needInt(Small))
	fmt.Println(needFloat(Small))
	fmt.Println(needFloat(Big))
}

func needInt(x int) int {
	return x * 10 + 1
}

func needFloat(x float64) float64 {
	return x * 0.1
}

// ---result---
// Happy 3.14 Day
// Go rules? true
// 21
// 0.2
// 1.2676506002282295e+29
----

== If

* c, java 와 비슷하지만 조건 표현시 `( )` 는 사용 안함
* 조건문 앞에 짧은 명령 실행 가능
+
--
[source, go]
----
if v := math.Pow(x, n); v < lim {
    ...
}
----

IMPORTANT: 조건문에서 선언된 변수는 `if-else` 문 안에서만 사용 가능
--

[source, go]
----
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(sqrt(2), sqrt(-4))
	fmt.Println(pow(3, 2, 10), pow(3, 3, 20))
}

func sqrt(x float64) string {
	if x < 0 {
		return sqrt(-x) + "i"
	}
	return fmt.Sprint(math.Sqrt(x))
}

func pow(x, n, lim float64) float64 {
	if v := math.Pow(x, n); v < lim { <1>
		return v
	} else {
		fmt.Printf("%g >= %g\n", v, lim)
	}
    // fmt.Printf(v) <2>
	return lim
}

// ---result---
// 1.4142135623730951 2i
// 27 >= 20
// 9 20
----
<1> 조건문에서 짧은 명령 실행
<2> if-else 문 밖에서는 v 변수 사용 불가

== For

* go 에서는 반복문이 `for` 밖에 없음
* `if` 문 처럼 c, java 와 유사하지만 조건문에 `( )` 가 필요 없음
* 전후처리를 제외하고 조건문만 표현 가능
* 조건문을 생략하면 무한 루프

[source, go]
----
package main

import "fmt"

func main() {
	sum := 0
	for i := 0; i < 10; i++ {
		sum += i
	}
	fmt.Println(sum)

	sum = 1
	for sum < 1000 { <1>
		sum += sum
	}
	fmt.Println(sum)

	sum = 1
	for { <2>
		sum += sum
		if sum > 100 {
			break
		}
	}
	fmt.Println(sum)
}

// ---result---
// 45
// 1024
// 128
----
<1> 조건문만 표현
<2> 무한 루프